apiVersion: v2
name: orders-service
description: Order processing service with external secrets
version: 0.1.0
type: application
dependencies:
  - name: platform-library
    version: "0.4.0"
    repository: "file://../../charts/platform-library"