name: notifications-service
team: platform-eng
slo_tier: "2"
on_call_channel: platform-eng-oncall
image:
  repository: 517121893325.dkr.ecr.us-east-1.amazonaws.com/notifications-service
  tag: "otel-048803a"
env:
  - name: OTEL_SERVICE_NAME
    value: notifications-service
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: http://otel-collector-opentelemetry-collector.logging:4317
  - name: OTEL_TRACES_EXPORTER
    value: otlp
  - name: OTEL_METRICS_EXPORTER
    value: none
  - name: OTEL_LOGS_EXPORTER
    value: none
port: 8000
replicaCount: 2
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
securityContext: {}
probes:
  readiness:
    path: /health
  liveness:
    path: /health
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  host: notifications.lab.local
rollout:
  enabled: true
  workloadRef:
    enabled: false
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 60s}
        - setWeight: 50
        - pause: {duration: 60s}
        - setWeight: 100
  analysis:
    templates:
      - templateName: success-rate
        clusterScope: true
      - templateName: latency-p99
        clusterScope: true
    args:
      - name: namespace
        value: notifications