{{- define "platform.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: platform
    platform.io/team: {{ required "A value for .Values.team is required" .Values.team | quote }}
    platform.io/slo-tier: {{ required "A value for .Values.slo_tier is required" .Values.slo_tier | quote }}
    platform.io/on-call: {{ required "A value for .Values.on_call_channel is required" .Values.on_call_channel | quote}}
spec:
  replicas: {{ if .Values.rollout.enabled }}0{{ else }}{{ .Values.replicaCount | default 2 }}{{ end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name | quote }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    {{- include "platform.podspec" . | nindent 4 }}
{{- end -}}