apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-services
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/rinatmyrzaliev/platform-golden-path.git
        revision: main
        directories:
          - path: services/*
  template:
    metadata:
      name: "{{ .path.basename }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/rinatmyrzaliev/platform-golden-path.git
        targetRevision: main
        path: "{{ . path }}"
        helm:
          releaseName: "{{ .path.basename }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .path.basename }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          