{{- if or (not (and .Values.rollout .Values.rollout.enabled)) (and .Values.rollout .Values.rollout.enabled .Values.rollout.workloadRef .Values.rollout.workloadRef.enabled) }}
{{ include "platform.deployment" . }}
{{- end }}